export const tinybirdPipes = [
  "list_traces",
  "span_hierarchy",
  "list_logs",
  "logs_count",
  "logs_facets",
  "error_rate_by_service",
  "get_service_usage",
  "list_metrics",
  "metric_time_series_sum",
  "metric_time_series_gauge",
  "metric_time_series_histogram",
  "metric_time_series_exp_histogram",
  "metrics_summary",
  "traces_facets",
  "traces_duration_stats",
  "service_overview",
  "services_facets",
  "errors_by_type",
  "error_detail_traces",
  "errors_facets",
  "errors_summary",
  "service_apdex_time_series",
  "custom_traces_timeseries",
  "custom_traces_breakdown",
  "custom_logs_timeseries",
  "custom_logs_breakdown",
  "custom_metrics_breakdown",
] as const

export type TinybirdPipe = (typeof tinybirdPipes)[number]
