/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServiceMapRouteImport } from './routes/service-map'
import { Route as SelectPlanRouteImport } from './routes/select-plan'
import { Route as QuickStartRouteImport } from './routes/quick-start'
import { Route as QueryBuilderLabRouteImport } from './routes/query-builder-lab'
import { Route as OrgRequiredRouteImport } from './routes/org-required'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracesIndexRouteImport } from './routes/traces/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as TracesTraceIdRouteImport } from './routes/traces/$traceId'
import { Route as ServicesServiceNameRouteImport } from './routes/services/$serviceName'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceMapRoute = ServiceMapRouteImport.update({
  id: '/service-map',
  path: '/service-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectPlanRoute = SelectPlanRouteImport.update({
  id: '/select-plan',
  path: '/select-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickStartRoute = QuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryBuilderLabRoute = QueryBuilderLabRouteImport.update({
  id: '/query-builder-lab',
  path: '/query-builder-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRequiredRoute = OrgRequiredRouteImport.update({
  id: '/org-required',
  path: '/org-required',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceNameRoute = ServicesServiceNameRouteImport.update({
  id: '/services/$serviceName',
  path: '/services/$serviceName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboards': typeof DashboardsRoute
  '/errors': typeof ErrorsRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/org-required': typeof OrgRequiredRoute
  '/query-builder-lab': typeof QueryBuilderLabRoute
  '/quick-start': typeof QuickStartRoute
  '/select-plan': typeof SelectPlanRoute
  '/service-map': typeof ServiceMapRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/services/$serviceName': typeof ServicesServiceNameRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/services/': typeof ServicesIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboards': typeof DashboardsRoute
  '/errors': typeof ErrorsRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/org-required': typeof OrgRequiredRoute
  '/query-builder-lab': typeof QueryBuilderLabRoute
  '/quick-start': typeof QuickStartRoute
  '/select-plan': typeof SelectPlanRoute
  '/service-map': typeof ServiceMapRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/services/$serviceName': typeof ServicesServiceNameRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/services': typeof ServicesIndexRoute
  '/traces': typeof TracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboards': typeof DashboardsRoute
  '/errors': typeof ErrorsRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/org-required': typeof OrgRequiredRoute
  '/query-builder-lab': typeof QueryBuilderLabRoute
  '/quick-start': typeof QuickStartRoute
  '/select-plan': typeof SelectPlanRoute
  '/service-map': typeof ServiceMapRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/services/$serviceName': typeof ServicesServiceNameRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/services/': typeof ServicesIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboards'
    | '/errors'
    | '/logs'
    | '/metrics'
    | '/org-required'
    | '/query-builder-lab'
    | '/quick-start'
    | '/select-plan'
    | '/service-map'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/services/$serviceName'
    | '/traces/$traceId'
    | '/services/'
    | '/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboards'
    | '/errors'
    | '/logs'
    | '/metrics'
    | '/org-required'
    | '/query-builder-lab'
    | '/quick-start'
    | '/select-plan'
    | '/service-map'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/services/$serviceName'
    | '/traces/$traceId'
    | '/services'
    | '/traces'
  id:
    | '__root__'
    | '/'
    | '/dashboards'
    | '/errors'
    | '/logs'
    | '/metrics'
    | '/org-required'
    | '/query-builder-lab'
    | '/quick-start'
    | '/select-plan'
    | '/service-map'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/services/$serviceName'
    | '/traces/$traceId'
    | '/services/'
    | '/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardsRoute: typeof DashboardsRoute
  ErrorsRoute: typeof ErrorsRoute
  LogsRoute: typeof LogsRoute
  MetricsRoute: typeof MetricsRoute
  OrgRequiredRoute: typeof OrgRequiredRoute
  QueryBuilderLabRoute: typeof QueryBuilderLabRoute
  QuickStartRoute: typeof QuickStartRoute
  SelectPlanRoute: typeof SelectPlanRoute
  ServiceMapRoute: typeof ServiceMapRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ServicesServiceNameRoute: typeof ServicesServiceNameRoute
  TracesTraceIdRoute: typeof TracesTraceIdRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-map': {
      id: '/service-map'
      path: '/service-map'
      fullPath: '/service-map'
      preLoaderRoute: typeof ServiceMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-plan': {
      id: '/select-plan'
      path: '/select-plan'
      fullPath: '/select-plan'
      preLoaderRoute: typeof SelectPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-start': {
      id: '/quick-start'
      path: '/quick-start'
      fullPath: '/quick-start'
      preLoaderRoute: typeof QuickStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-builder-lab': {
      id: '/query-builder-lab'
      path: '/query-builder-lab'
      fullPath: '/query-builder-lab'
      preLoaderRoute: typeof QueryBuilderLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org-required': {
      id: '/org-required'
      path: '/org-required'
      fullPath: '/org-required'
      preLoaderRoute: typeof OrgRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceName': {
      id: '/services/$serviceName'
      path: '/services/$serviceName'
      fullPath: '/services/$serviceName'
      preLoaderRoute: typeof ServicesServiceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardsRoute: DashboardsRoute,
  ErrorsRoute: ErrorsRoute,
  LogsRoute: LogsRoute,
  MetricsRoute: MetricsRoute,
  OrgRequiredRoute: OrgRequiredRoute,
  QueryBuilderLabRoute: QueryBuilderLabRoute,
  QuickStartRoute: QuickStartRoute,
  SelectPlanRoute: SelectPlanRoute,
  ServiceMapRoute: ServiceMapRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ServicesServiceNameRoute: ServicesServiceNameRoute,
  TracesTraceIdRoute: TracesTraceIdRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
